name: CpuThrottlingTest
options:
  bundleIdPrefix: com.granturismo
targets:
  CpuThrottlingTest:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: CpuThrottlingTest
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.granturismo.thermohammer
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "Gogita Kupatadze"
      CODE_SIGNING_ALLOWED: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
