name: CpuThrottlingTest
options:
  bundleIdPrefix: com.granturismo
targets:
  CpuThrottlingTest:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: CpuThrottlingTest
    postBuildScripts:
      - name: "Trick App Store Connect Xcode Beta check"
        script: |
          plist="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          if [ -f "$plist" ]; then
            echo "Modifying Info.plist DT keys for App Store Connect submission..."
            /usr/bin/plutil -replace DTXcode -string "1540" "$plist"
            /usr/bin/plutil -replace DTXcodeBuild -string "15F31d" "$plist"
            /usr/bin/plutil -replace DTSDKBuild -string "21F77" "$plist"
            /usr/bin/plutil -replace DTPlatformBuild -string "21F77" "$plist"
            /usr/bin/plutil -replace DTPlatformVersion -string "17.5" "$plist"
            /usr/bin/plutil -replace DTSDKName -string "iphoneos17.5" "$plist"
          fi
          touch "${DERIVED_FILE_DIR}/trick_asc_completed.txt"
        outputs:
          - "$(DERIVED_FILE_DIR)/trick_asc_completed.txt"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.granturismo.thermohammer
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "RJX83ALG73"
      CODE_SIGNING_ALLOWED: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      INFOPLIST_KEY_CFBundleDisplayName: "ThermoHammer"
      INFOPLIST_KEY_CFBundleName: "ThermoHammer"
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UIRequiresFullScreen: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations:
        - "UIInterfaceOrientationPortrait"
        - "UIInterfaceOrientationPortraitUpsideDown"
